name: sync up to codecommit in prod

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  betasync:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.BETA_CODECOMMIT_ROLE }}
          role-session-name: betarolesession
          aws-region: us-west-2
      - name: Sync up to CodeCommit
        uses: tsgit18/sync-up-to-codecommit-action@v1.0.6
        with:
          repository_name: GitHubServiceConnectAgent
          aws_region: us-west-2
  prodsync:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.PROD_CODECOMMIT_ROLE }}
          role-session-name: prodrolesession
          aws-region: us-west-2
      - name: Sync up to CodeCommit
        uses: tsgit18/sync-up-to-codecommit-action@v1.0.6
        with:
          repository_name: GitHubServiceConnectAgent
          aws_region: us-west-2
